### ISSUE TITLE
这是一个点赞issue

### ISSUE THREAD

**Issue by AllenBird** [phodal/mooa#1]
看了这个项目的介绍之后，是不是可以称之为前端的zookeeper?
另外，设计上，基座是需要区分于各个app独立部署来提供服务的吧？

**Comment by phodal** [comment]
从 zookeeper 的介绍上来说，和 zookeeper 相似。设计上，基座（ = 主工程 + Mooa）是用来管理 APP 的。

**Comment by AllenBird** [comment]
另外，前端会涉及到一部分load 和 router的功能，为啥要局限在ng呢？

**Comment by phodal** [comment]
@AllenBird Single-SPA 本身就是这样的一套方案，支持一系列的 Bootloader。Single-SPA 的设计是应用之间对等的，没有一个基座的概念。但是，真实场景下是会有基座这种东西，我们用的是 Angular，就基于 Angular 了。

**Comment by Ponicy** [comment]
不知道是不是我对微前端理解的偏差。

**Comment by Ponicy** [comment]
不知道是不是我对微前端理解有偏差。
我理解的是，一个app就是一个业务服务，它可以是独立部署，也可以嵌入第三方系统使用；
在一个管理app主程序容器上，配置一个二级app入口，即可访问业务服务；
看了下大佬的代码，我的理解上，感觉大佬像是app组件化，一个业务服务独立在一个组件中

**Comment by phodal** [comment]
@Ponicy 初衷是独立开发、独立部署、独立运行

**Comment by Ponicy** [comment]
@phodal 是碰到什么问题嘛？我现在在设想这个，想破了脑袋，觉得除了最常规iframe，想不到其他的方式做，跪了····

**Comment by phodal** [comment]
@Ponicy 那你就看一下这个、：https://github.com/phodal/microfrontends
