### ISSUE TITLE
标签重复插入及样式隔离问题

### ISSUE THREAD

**Issue by gaoupon** [phodal/mooa#11]
1.  一个小问题： mooa.phodal.com 中，应用切换时 `script` 和 `style` 标签重复插入了
2. 请教一下，微前端系统中需要做样式隔离吗，因为很有可能某个子应用会覆盖全局样式，光靠规范无法保证，我们之前有尝试使用 `shadow dom`，但是 `shadow dom` 只能隔离 `dom` 和 样式， 不能隔离 js, 现在很多应用都是通过打包工具使用 js 创建全局 style 标签，还是会有可能冲突问题~

**Comment by phodal** [comment]
1. 样式重复插件这个问题，依赖于你们是否有统一的样式？如果有统一的样式，建议在主工程中加入就可以了。
2. 如果要做样式隔离，可以采用 iframe 模式。如果是非 iframe 模式，得从规范解决问题，如每个子应用添加对应的前缀。

**Comment by gaoupon** [comment]
好的，关于样式隔离，可能现阶段只能通过 iframe 的方式了。

关于标签重复插入的问题，可能是我没有描述清楚：
![image](https://user-images.githubusercontent.com/8264905/48756138-d4117000-ecd2-11e8-8b44-c68d2ce280bd.png)
如上图所示是 mooa.phodal.com 这个示例网站的头部里内容，每次进入统一应用都会重新把 script 和 style
 插入一遍，造成很多重复的标签。

**Comment by phodal** [comment]
@gaoupon 重新检测了一下，发现是删除逻辑有问题。

**Comment by phodal** [comment]
@gaoupon 我这边修复了这个问题，你可以再试试

**Comment by gaoupon** [comment]
👍我这边没问题了
