### ISSUE TITLE
关于微前端的一些探讨

### ISSUE THREAD

**Issue by LiShuxue** [phodal/mooa#13]
Hi Phodal,

看了你的关于微前端的一些文章，《实施前端微服务化的六七种方式》《微前端快速选型指南》《【架构拾集】 微前端：微应用化》。

我们公司目前要做一个新的产品，计划使用微前端的架构，目前在探索阶段。

关于你说的微应用那块，其实我也比较想用这种，但是有一些疑问。

假如我们采用的vue框架，不同的模块用一个单独的vue应用实现，每个应用最后打包之后是一些css,js,和index.html，我怎么样把这些集成在那个主应用中呢？用iframe去加载这个index.html吗？这样不就还是Iframe的实现吗？

或者是说可能我没有get到您的点，能不能指点一下。

假如我有：

主应用
+ 子应用1
+ 子应用2
+ 子应用3

主应用和子应用都有业务代码，而且每一个都是SPA。
1. 子应用怎么集成，并最终产品表现为同一个应用
2. 主应用怎么路由到不同的子应用
3. 子应用与子应用之间，主应用与子应用之间，怎么通讯

我就职于一家大型外企，前端工作两三年了。但是微前端这块还没有研究过，网上查资料，目前也没有什么很成熟的解决方案。看到您在这块有很深的研究以及实践，所以期望您能给出点意见或者建议。谢谢了。

**Comment by phodal** [comment]
你们想要的方案，多深入尝试一些 Mooa 或者微应用化的方案，就可以实现了。

 - Mooa 即可以用 iframe 加载，也可以直接 DOM 加载多个应用。
 - 微应用化是运行时，在持续集成上结合代码的方式。

这个项目是 Mooa 框架相关的内容，有问题可以到 https://github.com/phodal/microfrontends 讨论。
