### ISSUE TITLE
子应用公共样式不起作用

### ISSUE THREAD

**Issue by bingo618** [phodal/mooa#14]
子应用使用了NG-ZORRO组件库，加载子应用时，UI样式没有出现

**Comment by phodal** [comment]
@bingo618 我不是很了解 NG-ZORROR 的 UI 样式是怎样的，是不是没有写入配置文件中？

**Comment by bingo618** [comment]
style文件已配置，发现加载在主应用中，但是样式没有显示。还有一个问题就是路由策略选择HashLocationStragegy ，子应用加载不了。

**Comment by phodal** [comment]
@bingo618 HashLocationStragegy 好像没有适配过。你们在生产环境里有这种需求？
