### ISSUE TITLE
Recovering from failure. 

### ISSUE THREAD

**Issue by GeoffSeloana** [phodal/mooa#18]
Hi,

It seems as if the child applications cannot reload when they fail. How can i ensure that the applications can load again when they fail?

How can the child applications recover from failure when they load.

Highly appreciate your assistance.

**Comment by phodal** [comment]
Actually, I don't have some assume about this. At the first, the child application can be load again. In my option, If a application can not be load, it will be a resources issue.

Can you provide some really use cases?

**Comment by GeoffSeloana** [comment]
Yes you are right. If an application cannot load then it is a resource issue. In my case the applications are not always available, sometimes they are offline. How do we implement a retry to be able to retry to load a child application again?

**Comment by phodal** [comment]
It's a business domain relative logic. In this case, I think you need to record a failure loading. And then, when you need, you can reload this application. But if you know time to reload application, you can just load application like first time.
