### ISSUE TITLE
能否实现多个应用分开打包独立部署的场景？

### ISSUE THREAD

**Issue by myzhibie** [phodal/mooa#2]
目前业务里面有一些子服务分开独立用Webpack打包，然后在一个主工程里面根据路由去加载子应用，但是加载的是子应用其中的一个路由，这样请求的JS只是一些异步的chunk，不包含初始化加载的runtime,vendor,main等bunddle,这样就相当于将分开打包独立部署的子应用又要合并到一个主应用里面，实施起来发现复杂的场景下坑很多，并不够健壮，因为webpack打包时依赖是预先确定的，并无法动态改变，所以常常加载子应用的某个功能时会因为缺少依赖而报错，这种情况下是否有可解决方案呢？

**Comment by phodal** [comment]
@myzhibie 如果每个子服务都包含了自己所需要的所有依赖，应该就不会有这样的问题。在这个项目里采用的就是这种做法，尽管会使构建出来的包大小变大。但是延迟一秒，远比报错来得好。
