### ISSUE TITLE
The serve command requires to be run in an Angular project, but a project definition could not be found.

### ISSUE THREAD

**Issue by succulen-plants** [phodal/mooa#20]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by phodal** [comment]
https://stackoverflow.com/questions/53096996/angular-cli-error-the-serve-command-requires-to-be-run-in-an-angular-project-b/53097004

**Comment by succulen-plants** [comment]
npm: 6.11.2
node: v11.15.0

npm uninstall -g @angular/cli
npm cache clean --force
npm install -g  @angular/cli@latest
ng update @angular/cli --migrate-only --from=1.4.7

There are still wrong：The serve command requires to be run in an Angular project, but a project definition could not be found.

**Comment by phodal** [comment]
新，这个和这个框架无关，你可以  Google 一下相关的解决方案
