### ISSUE TITLE
Not able to find the latest version

### ISSUE THREAD

**Issue by nikhiljj2018** [phodal/mooa#22]
Hey Phodal, I went through your article Micro-frontend Architecture in Action with six ways. I liked the article a lot. I went through mooa docs. When I saw the example. It looks like u upgraded the pages and mooa as well, but I check out the examples it looks like iframe version. Can you please help me I have 6 angular applications all deployed independently. I have to develop a shell where we can access the applications

**Comment by phodal** [comment]
just remove ``mode: 'iframe'`` config will be different

**Comment by nikhiljj2018** [comment]
I tried creating angular project with version 8 and I added the rest of the code present in examples, it is through some error can you share the share the example repository which have angular 8?

**Comment by phodal** [comment]
try https://github.com/worktile/ngx-planet
