### ISSUE TITLE
不同业务模块之间如何发送通知

### ISSUE THREAD

**Issue by nick121212** [phodal/mooa#6]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by phodal** [comment]
CustomEvent

**Comment by phodal** [comment]
@nick121212 如果使用的是 iframe 的话，可以这么用 https://github.com/phodal/microfrontend#%E5%8F%91%E5%B8%83%E4%B8%BB%E5%BA%94%E7%94%A8%E4%BA%8B%E4%BB%B6
