### ISSUE TITLE
几点疑问想请教一下

### ISSUE THREAD

**Issue by taomas** [phodal/mooa#8]
1. 请问这个框架目前有在生产环境上使用过吗？
2. 请问支持使用vue.js吗？我们部门统一的技术栈的vue.js，好像用不了这个。
3. 我看了一下`single-spa`的demo，好像里面的common-dependencies特别大，不知道这个会怎样？
4. 现在我有两个项目，里面有一些流程是基本一致的，想请教一下，适不适合用微服务来做。

其实主要就是想尝试一下微服务，感觉能解决不少前端的痛点，但是不清楚这个坑多不多。

**Comment by phodal** [comment]
1. 设计这个框架的时候，因为一些主观原因，没有在我们的项目上使用过。我们采用的是这个方案：《[【架构拾集】 微前端：微应用化](https://www.phodal.com/blog/architecutre-in-word-design-micro-application-frontend-architecture/)》，应该也会适合你们的。
2. 编写这个框架的时候，当前并不支持 Vue.js，稍微修改一下即可以使用。
3.  如果不是要提供 CLI 支持，这个框架的第三方依赖为 0 
4.  是否适合采用微服务，建议阅读一下《[微前端的那些事儿](https://github.com/phodal/microfrontends)》

坑，会有的，具体看场景。

**Comment by taomas** [comment]
感谢芬达大大的解答，我先看看您写的这些文章。先学习一下，后期熟悉了再尝试迁移到微前端。
